name: Hurtownie Sync

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC = 03:00 PL zimą
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Run synchronizers with smart operator gaps
        shell: bash
        run: |
          set -euo pipefail

          # --- USTAWIENIA ODSTĘPÓW ---
          MIN_GAP_AB=900      # 15 minut dla AB
          MIN_GAP_OTHER=30    # 30 sekund dla pozostałych (możesz zmienić na 0)

          # --- KOLEJNOŚĆ SYNCHRONIZATORÓW ---
          IDS=(2 3 4 8 9 17 15)

          # --- MAPOWANIE ID -> OPERATOR ---
          operator_for_id() {
            case "$1" in
              8|15|17) echo "AB" ;;
              4|9)     echo "ACTION" ;;
              2)       echo "NTT" ;;
              3)       echo "INCOM" ;;
              *)       echo "OTHER" ;;
            esac
          }

          # Zapamiętujemy czas startu operatorów
          declare -A last_start_ts

          echo "===== START SYNC $(date -u) UTC ====="

          for id in "${IDS[@]}"; do

            op="$(operator_for_id "$id")"
            url="https://www.pit-computers.pl/cron/productSynchronizer.php?synchronizer_id=${id}"

            now=$(date +%s)

            # wybierz minimalny odstęp
            if [[ "$op" == "AB" ]]; then
              min_gap=$MIN_GAP_AB
            else
              min_gap=$MIN_GAP_OTHER
            fi

            # sprawdź czy trzeba czekać
            if [[ -n "${last_start_ts[$op]+x}" ]]; then
              elapsed=$(( now - last_start_ts[$op] ))
              if (( elapsed < min_gap )); then
                wait=$(( min_gap - elapsed ))
                echo "Waiting ${wait}s (operator=$op)..."
                sleep "$wait"
              fi
            fi

            # zapisz start operatora
            last_start_ts[$op]=$(date +%s)

            echo "--------------------------------------"
            echo "START: $url"
            echo "TIME:  $(date -u) UTC (operator=$op)"

            curl -L --fail --max-time 7200 -sS "$url" || true

            echo "END:   $url"
          done

          echo "===== END SYNC ====="
